version: '3.9'

services:
  backend:
    build: ./backend
    container_name: url_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - minio   # เพิ่ม minio ขึ้นกับ backend

  frontend:
    build: ./frontend
    container_name: url_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@delta.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    depends_on:
      - db

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"       # MinIO API port
      - "9001:9001"       # MinIO Console (เว็บจัดการ)
    environment:
      MINIO_ROOT_USER: minioadmin    # ตั้งค่า Access Key (เปลี่ยนได้ตามต้องการ)
      MINIO_ROOT_PASSWORD: minioadmin # ตั้งค่า Secret Key (เปลี่ยนได้ตามต้องการ)
      MINIO_SERVER_URL: http://localhost:9000
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

volumes:
  pgdata:
  minio_data:
